language: node_js

node_js:
  - 'node'
  - '10'
  - '8'
  - '6'

script:
  - npm test

addons:
  code_climate:
    repo_token: 4140e6c153bcc97efb7e556a899b946fe7ed4fe3d19457a761e435423caa8c2c

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

jobs:
  include:
  - stage: npm release
    if: tag IS present
    node_js: '10'
    script: echo "Deploying to npm ..."
    after_script: skip
    deploy:
      provider: npm
      email: vatev.1+npm@gmail.com
      api_key:
        secure: X2F1xlYzqrae3kqlIX+7CNX8nj0ynoTULfBcwQjVPHMJhMGcZPnvfrfXnWu8MIZLNb2uYdY++UZFwLAc9vRaozINSDWYaIGaBnMiowW52cDa64ilf9b9+l8Ejce2WM0TBwifPhmavK4Y3TYaCT4ThjQr/WN9oJMsOCn/E+ZwJEPRVdyG0iz5cR/SEn/fbLuVFCy5+G9+nDU+XJbauW9yMu7fWv9FIDCSlkpF+fSkv/EEZSIBlg157uSkvtlizJDgK6u3aOsMQ3W8EnJPBjZhv5PRitW3qw199qRFewYsqb++pITy8NhhlljoOkc5vVGfAZamUapxOJF2GKtNH53L2gbnrm8+2cS5sHE5AjN2aQ66hUo1znOeGgeVQdAsGGXsURdVbucxHB/8y1LQd2xDRwV3t5ANaTt74EodBpot7NqJ+Ifh55YOxRc9j01G+MeMU0Pc2a0DJ9FtZAZv/8noaCFGYYgetRAFE9YyKoX9an8emrfbzlDEol61N7VCeesKrERI2RBe6nESH04ELyOvThDbtabK+kyF0ei7WHZOioit1vvZTMxzuOlPu56DWbqdRnBeFEOVQ3lStP8sIftAE+Bjs6Yd6bLOedhzevcclcXlouehx8srd2SMIErlGYVYydsPSGeHaY3C/TgpMlfBQTee0TxuX3G0iK77APiESLA=
      on:
        tags: true
        repo: catdad/multispawn
