language: node_js

node_js:
  - 'node'
  - '10'
  - '8'
  - '6'

script:
  - npm test

addons:
  code_climate:
    repo_token: 4140e6c153bcc97efb7e556a899b946fe7ed4fe3d19457a761e435423caa8c2c

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

jobs:
  include:
  - stage: npm release
    if: tag IS present
    node_js: '10'
    script: echo "Deploying to npm ..."
    after_script: skip
    deploy:
      provider: npm
      email: vatev.1+npm@gmail.com
      api_key:
        secure: OYXyS0uLVU4r4yRwwckrWBFuH2kC2pbhs0RwHQKrHnOOqZo2Uibypb8hMAr4t/+jhSX4l0Pm7OQV41Uno9Lz2xBBWhkTgws49zcJ7AsZQ6Qj9PnUth+7oLwxhgVw1Aurmwwg1r8sG/d/Bwsz/AdSku/fSCwhUIkIbhRfhkAUmGdvCFioVZ9jqX503KLO22Ve5AOXSY0fCFrIJ6zp1GRwZRrNE/U6aSepsAvywANe9OnL9XQ41Ay70VvbKX02C7YnZDxy8j/VIj0/AWaCWro8DIq/f7b8vvmUP6IDmk0eFnkFVxENfLbGAt+HQ3wuF1lQz1LaUgb+2igBsKtXr9rYKgq7CMp4e0FRhhzbrHDhtyvjiQZxrBmTr5JAczeyt2PBKVRDz72pzNLQCaFP5F2BK+eOzzu6ABCYe7o9IwFr/R22nwPcGMm0ivjlZwfnGp3VlCfcXGvdvuRxDtERFCCfzEZFrVZZptHMlM10lRsYO8CnhmECPlPm+TCGLt7f2ZyMw5/EM2FQ+N91lEs16Ik5/hzR/T0myZs8C807QqvsLNIS3C2QhPC0Ifu6u4w5UiXa46aMVHp5wwjaze/DDkZ+pwjt2PlbJWtzI1ABVQo1aY4micIr3Ju0Qnp2ohzuAS19quxZQrpZ7Yi82ZaT05c+SnvoBTaSZenB8XM0devQL0U=
      on:
        tags: true
        repo: catdad/multispawn
