language: node_js

node_js:
  - 'node'
  - '10'
  - '8'
  - '6'

script:
  - npm test

addons:
  code_climate:
    repo_token: 4140e6c153bcc97efb7e556a899b946fe7ed4fe3d19457a761e435423caa8c2c

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

jobs:
  include:
  - stage: npm release
    if: tag IS present
    node_js: '10'
    script: echo "Deploying to npm ..."
    after_script: skip
    deploy:
      provider: npm
      email: vatev.1+npm@gmail.com
      api_key:
        secure: ZHMm1760KbWRL3KWcCwk4cjAXGmoAPWrw6LDj7gCxlSUPOj1E70JH6Z6/cY2Pez23XJHawwdsk3Ae6ggGPXRMLmgmDpgHRCJ19bOQTjhLi5Z30O679kAOIsFL3SeeVYYZzDhiwARVqG44JaBSsrkZeFK0KmQUgKYhx+SCTrQT2Zqd/GjKt9ZKl2mcYi9tIBODi+ALsdy26PpSq5YohmMBmP37P4qux0EEKIAdU35clbL6V3I5DiKFrkf9NRGfC1xTdYNBONPGR0kxUhzVm+CuBT5zF8qfSbJkAS6NpufhufIt0Cg3jSyfPqmRGcs0igXy3r6F+RAVWVRdlSVm/dron8K6EWD6t+KKyHreksT2gIwnLY2zXzWo17gtDSSo8H8GUlQ8vbElwMoRATKvKHH3aQSWETsmPsT0psE4UokkvoWISlY/JJIFRtw3b/7J4gqzM29mmRJQvaqb1EQnyku4G9/Q3gevFnXPNCR+M+CvPe9KnCtuBZYMKvgLsyLEBM0Z/HaCSO5t4X01QdrsHml7fjoCTml4tAupQPQ/O/2DY6qtnC9kvEbu+h1CLbuAi0edAgCSNfHiUc3VLgNaihXf6KZ55lZJ0VrtAQ05cNddNf59stPcGsYXScwFzuM937CstqAPNacgaSFtKMOD4F9iRXnjacby8VW5LwnaVK6a7I=
      on:
        tags: true
        repo: catdad/multispawn
